import { db, certificateFields, normalize, type Env } from "./db";
import { clearCookie, currentAdmin, revoke, signIn, verifyPassword } from "./auth";
export type { Env } from "./db";
const json = (data: unknown, status = 200, headers: HeadersInit = {}) => new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json", ...headers } });
const codePattern = /^[0-9]{9}$/; const statuses = new Set(["valid", "expired", "revoked"]);
function origin(request: Request, env: Env) { return env.ALLOWED_ORIGIN || new URL(request.url).origin; }
function cors(request: Request, env: Env) { return { "Access-Control-Allow-Origin": origin(request, env), "Access-Control-Allow-Credentials": "true", "Access-Control-Allow-Headers": "Content-Type", "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS" }; }
async function body(request: Request) { try { return await request.json() as Record<string, unknown>; } catch { throw new Error("Invalid JSON body"); } }
function validate(input: Record<string, unknown>) { if (typeof input.full_name !== "string" || !input.full_name.trim() || typeof input.course_name !== "string" || !input.course_name.trim()) throw new Error("Full name and course are required."); for (const field of ["date_of_birth", "issue_date"]) if (input[field] && (typeof input[field] !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(input[field] as string))) throw new Error(`Invalid ${field}.`); if (input.status && !statuses.has(String(input.status))) throw new Error("Invalid status."); }
const row = (value: unknown) => value as Record<string, unknown>;
async function app(request: Request, env: Env): Promise<Response> { const url = new URL(request.url); const path = url.pathname; const sql = db(env); if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors(request, env) });
  if (request.method === "GET" && path === "/api/verify") { const code = url.searchParams.get("code") || ""; if (!codePattern.test(code)) return json({ error: "Certificate not found" }, 404); const rows = await sql.query(`SELECT ${certificateFields} FROM certificates WHERE code = $1 LIMIT 1`, [code]); return rows[0] ? json({ valid: true, certificate: normalize(row(rows[0])) }) : json({ error: "Certificate not found" }, 404); }
  if (path === "/api/admin/login" && request.method === "POST") { const input = await body(request); const email = typeof input.email === "string" ? input.email.trim().toLowerCase() : ""; const password = typeof input.password === "string" ? input.password : ""; const rows = await sql.query("SELECT id, email, password_hash FROM admins WHERE email = $1 LIMIT 1", [email]); const admin = rows[0] as { id: number; email: string; password_hash: string } | undefined; if (!admin || !(await verifyPassword(password, admin.password_hash))) return json({ error: "Invalid admin credentials." }, 401); const session = await signIn(env, admin.id); return json({ authenticated: true, admin: { email: admin.email } }, 200, { ...cors(request, env), "Set-Cookie": session.header }); }
  if (path === "/api/admin/logout" && request.method === "POST") { await revoke(request, env); return json({ ok: true }, 200, { ...cors(request, env), "Set-Cookie": clearCookie() }); }
  if (path === "/api/admin/me" && request.method === "GET") { const admin = await currentAdmin(request, env); return json(admin ? { authenticated: true, admin: { email: admin.email } } : { authenticated: false }, admin ? 200 : 401); }
  if (!path.startsWith("/api/admin/certificates")) return json({ error: "Not found" }, 404);
  const admin = await currentAdmin(request, env); if (!admin) return json({ error: "Not authenticated" }, 401);
  if (request.method === "GET" && path === "/api/admin/certificates") { const rows = await sql.query(`SELECT ${certificateFields} FROM certificates ORDER BY created_at DESC`); return json({ certificates: rows.map((r) => normalize(row(r))) }); }
  const match = path.match(/^\/api\/admin\/certificates\/([0-9]{9})$/); const code = match?.[1];
  if (request.method === "POST" && path === "/api/admin/certificates") { const input = await body(request); validate(input); for (let i = 0; i < 10; i++) { const generated = String(100000000 + Math.floor(Math.random() * 900000000)); try { const rows = await sql.query(`INSERT INTO certificates (code, full_name, passport_number, date_of_birth, course_name, issue_date, status) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING ${certificateFields}`, [generated, String(input.full_name).trim(), input.passport_number ? String(input.passport_number).trim() : null, input.date_of_birth || null, String(input.course_name).trim(), input.issue_date || null, input.status || "valid"]); return json({ certificate: normalize(row(rows[0])) }, 201); } catch (e) { if (!String(e).toLowerCase().includes("unique")) throw e; } } return json({ error: "Could not allocate a unique certificate code." }, 409); }
  if (!code) return json({ error: "Not found" }, 404);
  if (request.method === "GET") { const rows = await sql.query(`SELECT ${certificateFields} FROM certificates WHERE code = $1`, [code]); return rows[0] ? json({ certificate: normalize(row(rows[0])) }) : json({ error: "Certificate not found" }, 404); }
  if (request.method === "PUT") { const input = await body(request); validate(input); const rows = await sql.query(`UPDATE certificates SET full_name=$1, passport_number=$2, date_of_birth=$3, course_name=$4, issue_date=$5, status=$6 WHERE code=$7 RETURNING ${certificateFields}`, [String(input.full_name).trim(), input.passport_number ? String(input.passport_number).trim() : null, input.date_of_birth || null, String(input.course_name).trim(), input.issue_date || null, input.status || "valid", code]); return rows[0] ? json({ certificate: normalize(row(rows[0])) }) : json({ error: "Certificate not found" }, 404); }
  if (request.method === "DELETE") { const result = await sql.query("DELETE FROM certificates WHERE code = $1 RETURNING code", [code]); return result.length ? json({ ok: true }) : json({ error: "Certificate not found" }, 404); }
  return json({ error: "Method not allowed" }, 405);
}
export default { async fetch(request: Request, env: Env) { try { const response = await app(request, env); const headers = new Headers(response.headers); for (const [key, value] of Object.entries(cors(request, env))) headers.set(key, value); return new Response(response.body, { status: response.status, headers }); } catch (error) { console.error(error); return json({ error: "Internal server error" }, 500, cors(request, env)); } } };
